// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpPbSaJkbOLuR6jlPcjfq8sw9Cklwv3w',
    appId: '1:449276673179:web:b0fc49b7794f9c89fe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    authDomain: 'mikan-231b6.firebaseapp.com',
    storageBucket: 'mikan-231b6.appspot.com',
    measurementId: 'G-FV0PFBJ0EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvD_V0RqlB2joPvrWj6e7NcnGAMvuFen4',
    appId: '1:449276673179:android:c8fd622b4a76ab0ffe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    storageBucket: 'mikan-231b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLM6OQ7ic0hPST9H67yVoor-vl5D1EDs',
    appId: '1:449276673179:ios:cc4d005af981454efe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    storageBucket: 'mikan-231b6.appspot.com',
    iosBundleId: 'com.example.mikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLM6OQ7ic0hPST9H67yVoor-vl5D1EDs',
    appId: '1:449276673179:ios:d819906812eec0acfe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    storageBucket: 'mikan-231b6.appspot.com',
    iosBundleId: 'com.example.mikan.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkpPbSaJkbOLuR6jlPcjfq8sw9Cklwv3w',
    appId: '1:449276673179:web:4e32f279732789e7fe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    authDomain: 'mikan-231b6.firebaseapp.com',
    storageBucket: 'mikan-231b6.appspot.com',
    measurementId: 'G-EVDHE04Z3E',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBkpPbSaJkbOLuR6jlPcjfq8sw9Cklwv3w',
    appId: '1:449276673179:web:74594900af4b8fb2fe1a3e',
    messagingSenderId: '449276673179',
    projectId: 'mikan-231b6',
    authDomain: 'mikan-231b6.firebaseapp.com',
    storageBucket: 'mikan-231b6.appspot.com',
    measurementId: 'G-YHH8RP8VVF',
  );
}
